source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
xcodeproj 'Curation'
use_frameworks!

pod 'GoogleMaps'
pod 'RealmSwift'
pod 'AFNetworking', '~> 2.6.0'
pod 'Google/Analytics'
pod 'PageMenu'

