# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Curation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'RealmSwift'
  pod 'AFNetworking', '~> 2.6.0'
  pod 'Google/Analytics'
  pod 'PageMenu'
  pod 'SwiftyGif'

  # Pods for Curation

  target 'CurationTests' do
    inherit! :search_paths
    # Pods for testing
	use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'RealmSwift'
  pod 'AFNetworking', '~> 2.6.0'
  pod 'Google/Analytics'
  pod 'PageMenu'
  pod 'SwiftyGif'
  end

  target 'CurationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
